### ISSUE TITLE
'delete' does not remove an entry from files.json

### ISSUE THREAD

**Issue by gifuhabu** [9yokuro/wrm#2]
to reproduce
```
$ touch foo bar
$ wrm remove foo

# from README.md, it does not work
# It must be specified with the full trash path instead.
$ wrm delete foo
error: 'foo' no such file or directory

$ wrm delete ~/.config/wrm/trash/foo

# error occurred because the entry is still in ~/.config/wrm/files.json
$ wrm list
error: '~/.config/wrm/trash/foo' no such file or directory
```

Have you checked to see if it works properly?
I would also like to mention that recording information in a single file in `~/.config/wrm/files.json` may cause a race condition problem when deleted in parallel.
(Advisory locking would be necessary if saving to a single file.)

BTW, What is the motivation for developing this CLI?
Compared to the myriad of CLIs that already exist, there does not seem to be a single unique feature.

I tell you this because you may not know that these tools are already available.

most famous one
https://github.com/andreafrancia/trash-cli

written in Rust, can install by cargo
https://github.com/oberblastmeister/trashy
https://github.com/TD-Sky/conceal

If you knew they existed, I would recommend writing what makes it better than these.

**Comment by 9yokuro** [comment]
Thanks for the report.
I'll fix this wrong behavior as soon as possible.
I didn't know about existing projects but I will make this project better in the future.
Please let me know if there are any problems or recommendations .

**Comment by 9yokuro** [comment]
Hello.
I fixed this problem:
```
$ touch foo bar
$ wrm remove foo

# from README.md, it does not work
# It must be specified with the full trash path instead.
$ wrm delete foo
error: 'foo' no such file or directory

$ wrm delete ~/.config/wrm/trash/foo

# error occurred because the entry is still in ~/.config/wrm/files.json
$ wrm list
error: '~/.config/wrm/trash/foo' no such file or directory
```
Usage on README.md now works.

> I would also like to mention that recording information in a single file in ~/.config/wrm/files.json may cause a race condition problem when deleted in parallel.
(Advisory locking would be necessary if saving to a single file.)

I'll change the file structure. Please wait for a while.
